### PR TITLE
Update readme with a Django example

### PR DESCRIPTION
**Pull request by karimone**
A complete Django logging example

### CODE REVIEW

**Comment by kislyuk** [comment]
Thanks for the doc. It's slightly incomplete - can you add a line showing how the resulting `LOGGING` variable is used to configure the logging?

**Comment by karimone** [comment]
Not sure what you mean with `add a line showing how the resulting LOGGING variable is used to configure the logging`. 

If you check the Django documentation, the example of log setup are shown as I did for the readme (https://docs.djangoproject.com/en/1.11/topics/logging/)

In Django the settings is a module and the logging system is configured setting the LOGGING variable in the settings module.

If I have had the example I'm proposing in this pull request I would have saved at least a couple of hours, I'm sure a Django developer will appreciate.

**Comment by karimone** [comment]
Last but not least. Thank you for your package. Makes our logging wonderful to use.

**Comment by kislyuk** [comment]
Thanks. So can you add "In your Django project, add the following to `settings.py`:" before your code block? That way the doc is more clear.

**Comment by karimone** [comment]
Ok.

**Pull request merged**
