### PR TITLE
adding ability to pass through cloudwatch logs endpoint url to boto3

### PR DESCRIPTION
**Pull request by kristiandds**
Thank you for providing this library. I need the ability to configure the cloudwatch logs endpoint from the default boto3 configuration. Let me know if there are any additions needed to include this in the core library.

### CODE REVIEW

**Comment by kislyuk** [comment]
Thank you for your PR. Your PR is not merged because this functionality is already supported using the `boto3_session` argument.

**Comment by johndburk** [comment]
I also need this functionality in order to test functionality against localstack (`http://localhost:4586`); I can't see where/how to configure a boto3 Session object to set an endpoint_url to pass to the client method...

@kristiandds : were you able to get this working by passing in a pre-defined boto3 `Session` object?

**Comment by kislyuk** [comment]
Sorry, I can see how this is not trivial. Normally you would pass `endpoint_url` to `client()`, but that is hardcoded in the constructor. Instead, use the event bus (https://boto3.amazonaws.com/v1/documentation/api/latest/guide/events.html):

```
import watchtower, logging, boto3
logging.basicConfig(level=logging.INFO)

class CustomCWLClient:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._endpoint.host = "https://my-favorite-host"

def add_custom_client(base_classes, **kwargs):
    base_classes.insert(0, CustomCWLClient)

session = boto3.Session()
session.events.register('creating-client-class.logs', add_custom_client)

logger = logging.getLogger(__name__)
logger.addHandler(watchtower.CloudWatchLogHandler(boto3_session=session))
logger.info("Hi")
```
This uses a private attribute (which can probably be avoided with more botocore event bus trickery, but it would be complex). I'm open to an update to this PR that generalizes by adding a `logs_client_args` kwarg, which would be a dict to be passed to `client()`.

**Comment by johndburk** [comment]
Thanks for the quick response.  I'd like to vote for the `logs_client_args` kwarg, it feels much cleaner, and avoids accessing internals.

I had to resort to monkey-patching (which I usually avoid like the plague) the Session instance that's passed in via the `boto3_session` kwarg.  Sometimes testing is trickier than the code being tested...

```
LOCALSTACK_LOGS_URL = 'http://localhost:4586'

def patched_client(service, endpoint_url=LOCALSTACK_LOGS_URL, *args, **kwargs):
    return boto3.client(
        service,
        endpoint_url=endpoint_url,
        *args, **kwargs
    )

boto3_session = boto3.Session(**AWS_KWARGS)
boto3_session.client = patched_client
```

Thank you for this module; I had originally looked at both watchtower and logbeam, initially went with logbeam based solely on the ability to pass in the client rather than the session, but kept encountering InvalidSequenceTokenException issues with logbeam under load testing in AWS.   Switched over to watchtower, and no issues encountered (passed in 300 messages in a iteration 250ms loop), other than losing the ability to test against localstack.  Now that I've got that going as well, all is good.

**Comment by johndburk** [comment]
Once again, thank you, but for a different reason this time.  I read up more on the event bus, and have refactored my unit tests to use this `session.events.register` approach going forward.  Much better than monkey-patching boto3.client for a one-off test.

**Pull request closed without merging**
