### PR TITLE
drop support for EOL Python 3.5

### PR DESCRIPTION
**Pull request by terencehonles**

### CODE REVIEW

**Comment by terencehonles** [comment]
@kislyuk looks like you don't allow the test credentials to be provided to PRs. Not sure if that just requires you to re-run the test or how that works. I'm debugging a forking issue, but I noticed the package doesn't provide support for Python 2 so I figured it should also drop Python 3.5 since that is EoL (it actually was when Python 2 was dropped)

**Comment by kislyuk** [comment]
Hi, thanks for your PR. I do not drop support for prior versions nor introduce CI on pre-release versions of Python without a specific need. For example, dropping support for Python 3.5 would be justifiable if we introduced PEP 526 type annotations.

**Comment by kislyuk** [comment]
Also - you are correct that AWS credentials are not currently provided to PRs. I'm planning to re-enable that once I verify that the AWS credentials in the test account are appropriately scoped.

**Comment by terencehonles** [comment]
> Hi, thanks for your PR. I do not drop support for prior versions nor introduce CI on pre-release versions of Python without a specific need. For example, dropping support for Python 3.5 would be justifiable if we introduced PEP 526 type annotations.

I'm not sure I get not adding a test on `pre-release`. It may not fail and if it doesn't fail it makes sense to make sure there are no forwards incompatible changes.

**Comment by terencehonles** [comment]
> Hi, thanks for your PR. I do not drop support for prior versions nor introduce CI on pre-release versions of Python without a specific need. For example, dropping support for Python 3.5 would be justifiable if we introduced PEP 526 type annotations.

@kislyuk Do you mind re-opening this then?

**Comment by kislyuk** [comment]
> I'm not sure I get not adding a test on pre-release. It may not fail and if it doesn't fail it makes sense to make sure there are no forwards incompatible changes.

I appreciate the effort, but I will not add pre-release versions of Python to the CI for this project. It creates more work for me for an uncertain benefit. If a Python version is released that is incompatible with watchtower, we will deal with it then.

> @kislyuk Do you mind re-opening this then?

Can you clarify why you think this PR should be reopened?

**Comment by terencehonles** [comment]
@kislyuk because I already add types to this branch and you can't see that because this PR is closed.

**Comment by kislyuk** [comment]
OK, please open a new PR with the type hints and dropping Python 3.5.

**Comment by kislyuk** [comment]
@terencehonles are you still interested in reopening the PR? I am happy to merge type hint support if you have the time to finish this up. Otherwise please let me know and I can pull from your fork to see if I can finish it up.

**Pull request closed without merging**
