### PR TITLE
Switch to time.monotonic instead of time.time

### PR DESCRIPTION
**Pull request by nickrw**
This prevents the batch from waiting too long during daylight saving
changes or other reasons that could cause a clock to change during the
thread's lifetime.

I also included a commit which breaks out the requirements into two parts,
to avoid installing 'eight' which is only used in the tests.

### CODE REVIEW

**Comment by kislyuk** [comment]
I thought `time.time()` *was* monotonic for all practical intents and purposes. It's UTC based so not affected by timezones - am I wrong? And I'm disregarding the crazy possibilities of someone manually resetting the time, or using a non-smooth time adjustment instead of ntpd, or using some ancient native Windows API that resets after 49 days (?).

Are there practical scenarios that I missed?

**Comment by nickrw** [comment]
It won't be affected by DST/timezones - you're right, I didn't look into it deeply enough when I wrote that. Not sure about practical scenarios, it's not something affecting me, just the lack of explicitly using a monotonic clock jumped out at me when I was first reading the code.

If you don't want the extra dependency I understand as time.time is probably good enough in most cases. I note that amazon's awscli-cwlogs plugin uses time.time - though they can expect a high percentage of installs will be on amazon linux.

**Comment by kislyuk** [comment]
I would like to avoid the runtime dependency on eight though. If you could factor that out, I can merge that immediately.

**Comment by nickrw** [comment]
OK, I'll resubmit just the first commit

**Pull request closed without merging**
