### PR TITLE
Preventing the thread from going off the rails and running forever

### PR DESCRIPTION
**Pull request by newmaniese**

### CODE REVIEW

**Comment by kislyuk** [comment]
Can you please explain in detail the error that you see? As far as I know the code works as intended, and your commit introduces a logic error.

**Comment by newmaniese** [comment]
I see the logic error. This isn't working for me in python 2.7. The thread never breaks out of the `while True` loop.

Also, sometimes get this error:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build/bdist.macosx-10.10-x86_64/egg/watchtower/__init__.py", line 141, in batch_sender
    my_queue.task_done()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/Queue.py", line 64, in task_done
    raise ValueError('task_done() called too many times')
ValueError: task_done() called too many times
```

**Comment by kislyuk** [comment]
The thread is not supposed to break out of the loop. It's a daemon thread.

**Comment by kislyuk** [comment]
This should be fixed by #8. Thanks for reporting.

**Pull request closed without merging**
